# Generated by Django 5.2.14 on 2026-05-27 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DISPUTE_LOST', 'Dispute_lost'), ('No_SHOW', 'No_show'), ('EARLY_COMPLETION', 'Early_completion'), ('PAYMENT_ON_TIME', 'Payment_on_time')], default='NO_SHOW', max_length=50)),
                ('score_change', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Trust', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TrustEvent',
                'verbose_name_plural': 'TrustEvents',
                'ordering': ['-created_at'],
            },
        ),
    ]
