# Generated by Django 5.2.14 on 2026-05-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustevent',
            name='event_type',
            field=models.CharField(choices=[('DISPUTE_LOST', 'Dispute_lost'), ('NO_SHOW', 'No_show'), ('EARLY_COMPLETION', 'Early_completion'), ('PAYMENT_ON_TIME', 'Payment_on_time')], default='NO_SHOW', max_length=50),
        ),
        migrations.AlterField(
            model_name='trustevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
