# Generated by Django 5.2.14 on 2026-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_phone_number_user_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contracts_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
