# Generated by Django 5.2.14 on 2026-05-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_contracts_completed_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
