# Generated by Django 5.2.14 on 2026-05-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
